Add missing requirement pins
Fixes `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`
when starting the Agent since MarkupSafe 2.1 was released.